language: ruby
rvm:
  - 2.3.0
services:
  - postgresql
env:
  - TEST_DIRECTORY=spec/models
  - TEST_DIRECTORY=spec/features
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script:
  - xvfb-run bundle exec rspec $TEST_DIRECTORY
cache: bundler
sudo: false
